language: java
sudo: false
install: true
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - itests/.cargo
addons:
  hosts:
    - test.edelphi.fi
    
before_script:
  - . travis-before-script.sh
    
script:
  - . travis.sh

notifications:
  email: false