language: java
sudo: required
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - itests/.cargo
  - itests/.phantomjs
  - ".sonar"
  - sonar-scanner
  - keycloak-3.2.1.Final
addons:
  chrome: beta
  hosts:
  - test.edelphi.org
before_install:
- openssl aes-256-cbc -K $encrypted_8fa85fc2c779_key -iv $encrypted_8fa85fc2c779_iv
  -in travis-encrypted.tar.enc -out travis-encrypted.tar -d
- tar xvf travis-encrypted.tar
install:
- ". travis-install.sh"
before_script:
- ". travis-before-script.sh"
script:
- ". travis.sh"
after_success:
- ". travis-after-success.sh"
after_failure:
- ". travis-after-failure.sh"
notifications:
  email: false
