language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - itests/.cargo
  - .sonar
  - sonar-scanner
addons:
  hosts:
    - test.edelphi.fi

install:
  - . travis-install.sh
    
before_script:
  - . travis-before-script.sh
    
script:
  - . travis.sh
  
after_success:
- . travis-after-success.sh
  
after_failure:
- . travis-after-failure.sh

notifications:
  email: false