version: "3"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edelphi
      MYSQL_USER: edelphi      
      MYSQL_PASSWORD: password
  edelphi:
    hostname: ${HOST}
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysql
    environment:
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CLUSTER_PASSWORD: ${CLUSTER_PASSWORD}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_TLS: ${SMTP_TLS}
      KUBERNETES_NAMESPACE: ${KUBERNETES_NAMESPACE}
      JAVA_OPTS: ${JAVA_OPTS}
  keycloak:
    image: metatavu/keycloak:5.0.0
    container_name: keycloak
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_ADDR: mysql
      DB_PASSWORD: root
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
    volumes: 
      - ../keycloak-theme-metatavu:/opt/jboss/keycloak/themes/metatavu
      - ../keycloak-theme-edelphi:/opt/jboss/keycloak/themes/edelphi
volumes:
  db_data: {}