export const ACCESS_TOKEN_UPDATE = "ACCESS_TOKEN_UPDATE";
export type ACCESS_TOKEN_UPDATE = typeof ACCESS_TOKEN_UPDATE;

export const QUERY_VALIDATION_MESSAGE_UPDATE = "QUERY_VALIDATION_MESSAGE_UPDATE";
export type QUERY_VALIDATION_MESSAGE_UPDATE = typeof QUERY_VALIDATION_MESSAGE_UPDATE;