package fi.metatavu.edelphi.domainmodel.querylayout;

public enum QueryPageType {
  TEXT,
  FORM,
  EXPERTISE,
  THESIS_SCALE_1D,
  THESIS_SCALE_2D,
  THESIS_ORDER,
  THESIS_TIME_SERIE,
  THESIS_MULTI_SELECT,
  THESIS_TIMELINE,
  THESIS_GROUPING,
  THESIS_MULTIPLE_2D_SCALES,
  LIVE_2D,
  COLLAGE_2D
}
