/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PanelState = 'DESIGN' | 'IN_PROGRESS' | 'ENDED';

export const PanelState = {
    DESIGN: 'DESIGN' as PanelState,
    INPROGRESS: 'IN_PROGRESS' as PanelState,
    ENDED: 'ENDED' as PanelState
};
