/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PanelAccessLevel } from './panelAccessLevel';
import { PanelState } from './panelState';


export interface Panel { 
    readonly id?: number;
    name: string;
    readonly path?: string;
    description?: string;
    accessLevel: PanelAccessLevel;
    state: PanelState;
}
export interface PanelOpt { 
    readonly id?: number;
    name?: string;
    readonly path?: string;
    description?: string;
    accessLevel?: PanelAccessLevel;
    state?: PanelState;
}
