/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelObject } from './modelObject';
import { QueryPageType } from './queryPageType';


export interface QueryPage { 
    readonly id?: number;
    type?: QueryPageType;
    options?: ModelObject;
}
export interface QueryPageOpt { 
    readonly id?: number;
    type?: QueryPageType;
    options?: ModelObject;
}
