/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueryPageLive2DColor } from './queryPageLive2DColor';


export interface QueryPageLive2DAxis { 
    label?: string;
    color?: QueryPageLive2DColor;
    options?: Array<string>;
}
export interface QueryPageLive2DAxisOpt { 
    label?: string;
    color?: QueryPageLive2DColor;
    options?: Array<string>;
}
