/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type QueryPageLive2DAnswersVisibleOption = 'IMMEDIATELY' | 'AFTER_OWN_ANSWER';

export const QueryPageLive2DAnswersVisibleOption = {
    IMMEDIATELY: 'IMMEDIATELY' as QueryPageLive2DAnswersVisibleOption,
    AFTEROWNANSWER: 'AFTER_OWN_ANSWER' as QueryPageLive2DAnswersVisibleOption
};
