/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type QueryPageType = 'TEXT' | 'FORM' | 'EXPERTISE' | 'THESIS_SCALE_1D' | 'THESIS_SCALE_2D' | 'THESIS_ORDER' | 'THESIS_TIME_SERIE' | 'THESIS_MULTI_SELECT' | 'THESIS_TIMELINE' | 'THESIS_GROUPING' | 'THESIS_MULTIPLE_2D_SCALES' | 'LIVE_2D' | 'COLLAGE_2D';

export const QueryPageType = {
    TEXT: 'TEXT' as QueryPageType,
    FORM: 'FORM' as QueryPageType,
    EXPERTISE: 'EXPERTISE' as QueryPageType,
    THESISSCALE1D: 'THESIS_SCALE_1D' as QueryPageType,
    THESISSCALE2D: 'THESIS_SCALE_2D' as QueryPageType,
    THESISORDER: 'THESIS_ORDER' as QueryPageType,
    THESISTIMESERIE: 'THESIS_TIME_SERIE' as QueryPageType,
    THESISMULTISELECT: 'THESIS_MULTI_SELECT' as QueryPageType,
    THESISTIMELINE: 'THESIS_TIMELINE' as QueryPageType,
    THESISGROUPING: 'THESIS_GROUPING' as QueryPageType,
    THESISMULTIPLE2DSCALES: 'THESIS_MULTIPLE_2D_SCALES' as QueryPageType,
    LIVE2D: 'LIVE_2D' as QueryPageType,
    COLLAGE2D: 'COLLAGE_2D' as QueryPageType
};
