/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface QueryPageLive2DAxis { 
    label?: string;
    color?: string;
}
export interface QueryPageLive2DAxisOpt { 
    label?: string;
    color?: string;
}
