/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type QueryState = 'EDIT' | 'ACTIVE' | 'CLOSED';

export const QueryState = {
    EDIT: 'EDIT' as QueryState,
    ACTIVE: 'ACTIVE' as QueryState,
    CLOSED: 'CLOSED' as QueryState
};
