/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueryPageLive2DAxis } from './queryPageLive2DAxis';


export interface QueryPageLive2DOptions { 
    axisX?: QueryPageLive2DAxis;
    axisY?: QueryPageLive2DAxis;
    min?: number;
    max?: number;
    precision?: number;
}
export interface QueryPageLive2DOptionsOpt { 
    axisX?: QueryPageLive2DAxis;
    axisY?: QueryPageLive2DAxis;
    min?: number;
    max?: number;
    precision?: number;
}
