/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type QueryPageLive2DColor = 'RED' | 'GREEN' | 'BLUE';

export const QueryPageLive2DColor = {
    RED: 'RED' as QueryPageLive2DColor,
    GREEN: 'GREEN' as QueryPageLive2DColor,
    BLUE: 'BLUE' as QueryPageLive2DColor
};
