/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ReportFormat = 'PDF' | 'CSV' | 'GOOGLE_SHEETS';

export const ReportFormat = {
    PDF: 'PDF' as ReportFormat,
    CSV: 'CSV' as ReportFormat,
    GOOGLESHEETS: 'GOOGLE_SHEETS' as ReportFormat
};
