/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ReportType = 'TEXT' | 'SPREADSHEET' | 'IMAGES';

export const ReportType = {
    TEXT: 'TEXT' as ReportType,
    SPREADSHEET: 'SPREADSHEET' as ReportType,
    IMAGES: 'IMAGES' as ReportType
};
