/**
 * eDelphi REST API
 * REST API for eDelphi
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReportDelivery } from './reportDelivery';
import { ReportFormat } from './reportFormat';


export interface ReportRequest { 
    panelId: number;
    queryId: number;
    queryPageId?: number;
    /**
     * Panel stamp id. Defaults to current stamp
     */
    stampId?: number;
    format?: ReportFormat;
    delivery?: ReportDelivery;
}
export interface ReportRequestOpt { 
    panelId?: number;
    queryId?: number;
    queryPageId?: number;
    /**
     * Panel stamp id. Defaults to current stamp
     */
    stampId?: number;
    format?: ReportFormat;
    delivery?: ReportDelivery;
}
