INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select IFNULL(max(id), 0) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'expertise') from QueryPageSettingKey where name = 'expertise.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale1d') from QueryPageSettingKey where name = 'scale1d.type';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'scale2d.type';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.maxY';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '100';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.maxX';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '2020';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.minY';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.minX';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '2010';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.stepX';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.stepY';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '5';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.userStepX';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.yTickDecimals';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '2';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'timeline.min';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'timeline.max';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '100';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'timeline.step';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale1d') from QueryPageSettingKey where name = 'thesis.commentable';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale1d') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'thesis.commentable';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'thesis.commentable';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'thesis.commentable';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'grouping') from QueryPageSettingKey where name = 'thesis.commentable'; 
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'grouping') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'multiselect') from QueryPageSettingKey where name = 'thesis.commentable';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'multiselect') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'ordering') from QueryPageSettingKey where name = 'thesis.commentable';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'ordering') from QueryPageSettingKey where name = 'thesis.showLiveReport';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'text') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'expertise') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale1d') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'grouping') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'multiselect') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'ordering') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'multiple2dscales') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, 1 from QueryPageSettingKey where name = 'text.content';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Text --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Teksti --' , 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale1d') from QueryPageSettingKey where name = 'scale1d.label';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Text --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Teksti --' , 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale1d') from QueryPageSettingKey where name = 'scale1d.options';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '---&--&-&%2B/-&%2B&%2B%2B&%2B%2B%2B' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '---&--&-&%2B/-&%2B&%2B%2B&%2B%2B%2B' , 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'scale2d.label.x';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Text --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Teksti --' , 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'scale2d.label.y';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Text --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Teksti --' , 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'scale2d.options.x';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '---&--&-&%2B/-&%2B&%2B%2B&%2B%2B%2B', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '---&--&-&%2B/-&%2B&%2B%2B&%2B%2B%2B', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'scale2d') from QueryPageSettingKey where name = 'scale2d.options.y';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '---&--&-&%2B/-&%2B&%2B%2B&%2B%2B%2B', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '---&--&-&%2B/-&%2B&%2B%2B&%2B%2B%2B', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.xAxisTitle';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Label --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Lis&#228;&#228; otsikko --' , 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.yAxisTitle';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Label --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Lis&#228;&#228; otsikko --', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.predefinedSetLabel';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Label --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Lis&#228;&#228; otsikko --', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeserie') from QueryPageSettingKey where name = 'time_serie.userSetLabel';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Insert Label --' , 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '-- Lis&#228;&#228; otsikko --', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'grouping') from QueryPageSettingKey where name = 'grouping.groups';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Group%201&Group%202', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Ryhm&#228;%201&Ryhm&#228;%202', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'grouping') from QueryPageSettingKey where name = 'grouping.items';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Item%201&Item%202&Item%203&Item%204&Item%205', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Valinta%201&Valinta%202&Valinta%203&Valinta%204&Valinta%205', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'multiselect') from QueryPageSettingKey where name = 'multiselect.options';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Multiselect%20option%201&Multiselect%20option%202&Multiselect%20option%203&Multiselect%20option%204&Multiselect%20option%205', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Valinta%201&Valinta%202&Valinta%203&Valinta%204&Valinta%205', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'ordering') from QueryPageSettingKey where name = 'orderingField.items';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Item%201&Item%202&Item%203&Item%204&Item%205', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), 'Valinta%201&Valinta%202&Valinta%203&Valinta%204&Valinta%205', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select max(id) + 1, 'Lomake', 'fi', (select max(id) from LocalizedEntry) from LocalizedValue;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select max(id) + 1, 'Form', 'en', (select max(id) from LocalizedEntry) from LocalizedValue;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select max(id) + 1, (select id from QueryPageSettingKey where name = 'visible'), (select id from QueryPageTemplate where iconName = 'form') from QueryPageTemplateSetting;
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select max(id) + 1, 'Taustatietolomake', 'fi', (select max(id) from LocalizedEntry) from LocalizedValue;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select max(id) + 1, 'Background Information Form', 'en', (select max(id) from LocalizedEntry) from LocalizedValue;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select max(id) + 1, (select id from QueryPageSettingKey where name = 'form.fields'), (select id from QueryPageTemplate where iconName = 'backgroundinformationform') from QueryPageTemplateSetting;
INSERT INTO LocalizedEntry select max(id) + 1 from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '[{"type":"LIST","caption":"Sex","options":[{"label":"Male","value":"NEW-0"},{"label":"Female","value":"NEW-1"}],"listType":"RADIO","name":"1"},{"type":"LIST","caption":"Age","options":[{"label":"10-14","value":"NEW-0"},{"label":"15-24","value":"NEW-1"},{"label":"25-44","value":"NEW-2"},{"label":"45-64","value":"NEW-3"},{"label":"65-","value":"NEW-4"}],"listType":"RADIO","name":"2"},{"type":"LIST","caption":"Status","options":[{"label":"Employed","value":"NEW-0"},{"label":"Unemployed","value":"NEW-1"},{"label":"Student","value":"NEW-2"},{"label":"Retired","value":"NEW-3"}],"listType":"RADIO","name":"3"},{"type":"LIST","caption":"Level of education","options":[{"label":"Pre-primary education","value":"NEW-0"},{"label":"Primary education","value":"NEW-1"},{"label":"Lower secondary education","value":"NEW-2"},{"label":"Upper secondary level education","value":"NEW-3"},{"label":"Lowest level tertiary education","value":"NEW-4"},{"label":"Lower-degree level tertiary education","value":"NEW-5"},{"label":"Higher-degree level tertiary education","value":"NEW-6"},{"label":"Doctorate or equivalent level tertiary education","value":"NEW-7"},{"label":"Level of education unknown","value":"NEW-8"}],"listType":"RADIO","name":"4"},{"type":"LIST","caption":"Region","options":[{"label":"Uusimaa","value":"NEW-0"},{"label":"Varsinais-Suomi","value":"NEW-1"},{"label":"Satakunta","value":"NEW-2"},{"label":"Kanta-H&#228;me","value":"NEW-3"},{"label":"Pirkanmaa","value":"NEW-4"},{"label":"P&#228;ij&#228;t-H&#228;me","value":"NEW-5"},{"label":"Kymenlaakso","value":"NEW-6"},{"label":"South Karelia","value":"NEW-7"},{"label":"Etel&#228;-Savo","value":"NEW-8"},{"label":"Pohjois-Savo","value":"NEW-9"},{"label":"North Karelia","value":"NEW-10"},{"label":"Central Finland","value":"NEW-11"},{"label":"South Ostrobothnia","value":"NEW-12"},{"label":"Ostrobothnia","value":"NEW-13"},{"label":"Central Ostrobothnia","value":"NEW-14"},{"label":"North Ostrobothnia","value":"NEW-15"},{"label":"Kainuu","value":"NEW-16"},{"label":"Lapland","value":"NEW-17"},{"label":"&#197;land","value":"NEW-18"}],"listType":"RADIO","name":"5"}]', 'en', max(id) from LocalizedEntry;
INSERT INTO LocalizedValue (id, text, locale, entry_id) select (select max(id) + 1 from LocalizedValue), '[{"type":"LIST","listType":"RADIO","name":"0","caption":"Sukupuoli","options":[{"label":"Mies","value":"0"},{"label":"Nainen","value":"1"}]},{"type":"LIST","listType":"RADIO","name":"1","caption":"Ik&#228;kausi","options":[{"label":"10-14 vuotta","value":"0"},{"label":"15-24 vuotta","value":"1"},{"label":"25-44 vuotta","value":"2"},{"label":"45-64 vuotta","value":"3"},{"label":"65-","value":"4"}]},{"type":"LIST","listType":"RADIO","name":"2","caption":"Asema","options":[{"label":"Ty&#246;llinen","value":"0"},{"label":"Ty&#246;t&#246;n","value":"1"},{"label":"Opiskelija","value":"2"},{"label":"El&#228;kel&#228;inen","value":"3"}]},{"type":"LIST","listType":"RADIO","name":"3","caption":"Koulutusaste","options":[{"label":"Esiaste","value":"0"},{"label":"Alempi perusaste","value":"1"},{"label":"Ylempi perusaste","value":"2"},{"label":"Keskiaste","value":"3"},{"label":"Alin korkea-aste","value":"4"},{"label":"Alempi korkeakouluaste","value":"5"},{"label":"Ylempi korkeakouluaste","value":"6"},{"label":"Tutkijakoulutusaste","value":"7"},{"label":"Koulutusaste tuntematon","value":"NEW-0"}]},{"type":"LIST","listType":"RADIO","name":"4","caption":"Maakunta","options":[{"label":"Uusimaa","value":"0"},{"label":"Varsinais-Suomi","value":"1"},{"label":"Satakunta","value":"2"},{"label":"Kanta-H&#228;me","value":"3"},{"label":"Pirkanmaa","value":"4"},{"label":"P&#228;ij&#228;t-H&#228;me","value":"5"},{"label":"Kymenlaakso","value":"6"},{"label":"Etel&#228;-Karjala","value":"7"},{"label":"Etel&#228;-Savo","value":"8"},{"label":"Pohjois-Savo","value":"9"},{"label":"Pohjois-Karjala","value":"10"},{"label":"Keski-Suomi","value":"11"},{"label":"Etel&#228;-Pohjanmaa","value":"12"},{"label":"Pohjanmaa","value":"13"},{"label":"Keski-Pohjanmaa","value":"14"},{"label":"Pohjois-Pohjanmaa","value":"15"},{"label":"Kainuu","value":"16"},{"label":"Lappi","value":"17"},{"label":"Ahvenanmaa - &#197;land","value":"18"}]}]', 'fi', max(id) from LocalizedEntry;
INSERT INTO QueryPageTemplateLocalizedSetting (id, value_id) select (select max(id) from QueryPageTemplateSetting) as id, (select max(id) from LocalizedEntry) as value_id;
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select max(id) + 1, (select id from QueryPageSettingKey where name = 'visible'), (select id from QueryPageTemplate where iconName = 'backgroundinformationform') from QueryPageTemplateSetting;
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'timeline') from QueryPageSettingKey where name = 'timeline.type';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '0';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.includedPages';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.pageSettings';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.replySource';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), 'ALL';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.labelVisibility';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), 'HOVER';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.replyCountsVisible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), 'TRUE';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.dotOffset';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'collage2d.dotMultiplier';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';
INSERT INTO QueryPageTemplateSetting (id, key_id, queryPageTemplate_id) select (select max(id) + 1 from QueryPageTemplateSetting), id, (select id from QueryPageTemplate where iconName = 'collage2d') from QueryPageSettingKey where name = 'visible';
INSERT INTO QueryPageTemplateSimpleSetting (id, value) select (select max(id) from QueryPageTemplateSetting), '1';

DELETE FROM hibernate_sequences WHERE sequence_name in ('QueryPageTemplateSetting', 'QueryPageTemplateSimpleSetting', 'LocalizedEntry', 'QueryPageTemplateLocalizedSetting');
INSERT INTO hibernate_sequences (sequence_next_hi_value, sequence_name) select max(id) + 1, 'QueryPageTemplateSetting' from QueryPageTemplateSetting;
INSERT INTO hibernate_sequences (sequence_next_hi_value, sequence_name) select max(id) + 1, 'QueryPageTemplateSimpleSetting' from QueryPageTemplateSimpleSetting;
INSERT INTO hibernate_sequences (sequence_next_hi_value, sequence_name) select max(id) + 1, 'LocalizedEntry' from LocalizedEntry;
INSERT INTO hibernate_sequences (sequence_next_hi_value, sequence_name) select max(id) + 1, 'QueryPageTemplateLocalizedSetting' from QueryPageTemplateLocalizedSetting;